---
title: "gam_modeling"
author: "darya akimova"
date: "9/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

## Packages:

```{r packages, comment=NA}
library(tidyverse)
library(viridis)
library(sf)
library(mgcv)
theme_set(theme_minimal())
```


## Data:

```{r data_import, comment=NA}
death_and_acs_data <- read_csv("../../../data/tidy_data/death_count_norm_to_pop_and_acs_town_demographics_merge.csv")
ma_town_coord <- read_csv("../../../data/tidy_data/ma_town_crs4326_coords.csv")
opi_pres_13 <- read_csv("../../../data/tidy_data/medicare_partD_opioid_prescriber_2013_w_zip_MAtown_v1.csv") %>% 
  select(-1)
opi_pres_14 <- read_csv("../../../data/tidy_data/medicare_partD_opioid_prescriber_2014_w_zip_MAtown_v1.csv") %>% 
  select(-1)
opi_pres_15 <- read_csv("../../../data/tidy_data/medicare_partD_opioid_prescriber_2015_w_zip_MAtown_v1.csv") %>% 
  select(-1)
opi_pres_16 <- read_csv("../../../data/tidy_data/medicare_partD_opioid_prescriber_2016_w_zip_MAtown_v1.csv") %>% 
  select(-1)
opi_pres_17 <- read_csv("../../../data/tidy_data/medicare_partD_opioid_prescriber_2017_w_zip_MAtown_v1.csv") %>% 
  select(-1)
ma_town_map <- st_read("../../../data/raw_data/townssurvey_shp/TOWNSSURVEY_POLYM.shp")
acs_medicare_opioid_merge <- read_csv("../../../data/tidy_data/acs_medicare_opioid_stats_death_rate.csv")
```


# EDA and Feature Engineering

## Data structure

```{r data_glimpse, comment=NA}
glimpse(death_and_acs_data)
glimpse(ma_town_coord)
glimpse(opi_pres_13)
glimpse(opi_pres_14)
glimpse(opi_pres_15)
glimpse(opi_pres_16)
glimpse(opi_pres_17)
```


## Joining datasets

```{r}
acs_data_w_geospatial <- death_and_acs_data %>% 
  inner_join(ma_town_coord, by = c("city_death" = "town"))
ma_town_map_w_data <- ma_town_map %>% 
  st_transform(crs = "+init=epsg:4326") %>% 
  mutate(TOWN = str_to_lower(TOWN)) %>% 
  left_join(death_and_acs_data, by = c("TOWN" = "city_death"))
```


```{r mapping, comment=NA}
ma_town_map_w_data$death_rate_18_cut <- as.character(cut(ma_town_map_w_data$death_rate_18, breaks = seq(0, 15, 5), include.lowest = TRUE))


ma_town_map_w_data %>%
  ggplot() +
  geom_sf(aes(fill = death_rate_18_cut), color = "black") +
  scale_fill_viridis_d(option = "D", name = "Rate") +
  theme(axis.text.x = element_blank(), axis.text.y = element_blank()) +
  ggtitle("Opioid overdose death rate per 10k residents\n2018")
ma_town_map_w_data %>%
  ggplot() +
  geom_sf(aes(fill = death_rate_17), color = "black") +
  scale_fill_viridis_c(option = "D", name = "Rate") +
  theme(axis.text.x = element_blank(), axis.text.y = element_blank()) +
  ggtitle("Opioid overdose death rate per 10k town residents\n2017")
ma_town_map_w_data %>%
  ggplot() +
  geom_sf(aes(fill = death_rate_16), color = "black") +
  scale_fill_viridis_c(option = "D", name = "Rate") +
  theme(axis.text.x = element_blank(), axis.text.y = element_blank()) +
  ggtitle("Opioid overdose death rate per 10k town residents\n2016")
ma_town_map_w_data %>%
  ggplot() +
  geom_sf(aes(fill = death_rate_15), color = "black") +
  scale_fill_viridis_c(option = "D", name = "Rate") +
  theme(axis.text.x = element_blank(), axis.text.y = element_blank()) +
  ggtitle("Opioid overdose death rate per 10k town residents\n2015")
ma_town_map_w_data %>%
  ggplot() +
  geom_sf(aes(fill = death_rate_14), color = "black") +
  scale_fill_viridis_c(option = "D", name = "Rate") +
  theme(axis.text.x = element_blank(), axis.text.y = element_blank()) +
  ggtitle("Opioid overdose death rate per 10k town residents\n2014")
ma_town_map_w_data %>%
  ggplot() +
  geom_sf(aes(fill = death_rate_13), color = "black") +
  scale_fill_viridis_c(option = "D", name = "Rate") +
  theme(axis.text.x = element_blank(), axis.text.y = element_blank()) +
  ggtitle("Opioid overdose death rate per 10k town residents\n2013")
```


```{r}
# death rate change calculations:
data_for_mod <- acs_data_w_geospatial %>% 
  mutate(
    diff_18_17 = death_rate_18 - death_rate_17,
    diff_17_16 = death_rate_17 - death_rate_16,
    diff_16_15 = death_rate_16 - death_rate_15,
    diff_15_14 = death_rate_15 - death_rate_14,
    diff_14_13 = death_rate_14 - death_rate_13
  ) %>% 
  select(-c(death_rate_12:death_rate_18)) %>% 
  gather(key = "years_chng", value = "diff", diff_18_17:diff_14_13) %>% 
  mutate(
    year = case_when(
      years_chng == "diff_18_17" ~ 2017,
      years_chng == "diff_17_16" ~ 2016,
      years_chng == "diff_16_15" ~ 2015,
      years_chng == "diff_15_14" ~ 2014,
      years_chng == "diff_14_13" ~ 2013,
    )
  ) %>% 
  select(-years_chng) %>% 
  mutate(id = row_number())
data_for_mod %>% 
  mutate(year = as_factor(year)) %>% 
  ggplot(aes(year, diff, group = year, fill = year)) +
  geom_violin() 
data_for_mod %>% 
  mutate(year = as_factor(year)) %>% 
  ggplot(aes(year, diff, group = year, fill = year)) +
  geom_boxplot() 
data_for_mod %>% 
  mutate(year = as_factor(year)) %>% 
  ggplot(aes(diff, fill = year)) +
  geom_histogram(bins = 50) +
  facet_wrap(~ year)
```


# Modeling


## Test - train split

```{r}
set.seed(2019)
test_set <- data_for_mod %>% 
  sample_frac(0.2, replace = FALSE)
train_set <- data_for_mod %>% 
  filter(!(id %in% (test_set$id)))
```


## Model - only acs and geospatial data

```{r}
# base model with geometry and year only
base_model <- gam(diff ~ s(x, y) + s(year, k=3), data = train_set, method = "REML")
summary(base_model)
mean(abs(train_set$diff - predict(base_model, train_set, type = "response")))
base_model_sel <- gam(diff ~ s(x, y) + s(year, k=3), data = train_set, method = "REML", select = TRUE)
summary(base_model_sel)
coef(base_model_sel)
# mae:
mean(abs(train_set$diff - predict(base_model_sel, train_set, type = "response")))
plot(base_model_sel, residuals = TRUE, pages = 1)
```


```{r}
all_acs_model <- gam(
  diff ~ s(x, y) + year + s(over_65_prop) + s(med_house_inc) + s(mean_house_inc) + s(mean_med_inc_desp) +
    s(drop_out) + s(less_than_hs_ed) + s(at_or_below_pov_prop) + s(pop_struggling_prop) + town_status + urb_v_rur,
  data = train_set, method = "REML", select = TRUE
  )
summary(all_acs_model)
mean(abs(train_set$diff - predict(all_acs_model, train_set, type = "response")), na.rm = TRUE)
train_set$predict_all_mod <- predict(all_acs_model, train_set, type = "response")
train_set %>% 
  ggplot(aes(diff, predict_all_mod)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0)
gam.check(all_acs_model)
concurvity(all_acs_model)
```


```{r}
train_mean_diff <- train_set %>% 
  group_by(city_death) %>% 
  summarise(mean_diff = mean(diff)) %>% 
  inner_join(
    train_set %>% 
      select(-c(diff:predict_all_mod)) %>% 
      distinct(),
    by = "city_death"
  ) %>% 
  mutate(
    town_status = as_factor(town_status),
    urb_v_rur = as_factor(urb_v_rur)
  )
all_acs_mean_model <- gam(
  mean_diff ~ s(x, y) + s(over_65_prop) + s(med_house_inc) + s(mean_house_inc) + s(mean_med_inc_desp) +
    s(drop_out) + s(less_than_hs_ed) + s(at_or_below_pov_prop) + s(pop_struggling_prop) + town_status + urb_v_rur,
  data = train_mean_diff, method = "REML", select = TRUE
  )
summary(all_acs_mean_model)
gam.check(all_acs_mean_model)
concurvity(all_acs_mean_model)
mean(abs(train_mean_diff$mean_diff - predict(all_acs_mean_model, train_mean_diff, type = "response")), na.rm = TRUE)
```












```{r,eval=FALSE}
acs_medicare_opioid_merge %>% 
  mutate(year = as_factor(year)) %>% 
  ggplot(aes(death_rate_per10k)) +
  geom_histogram() +
  facet_wrap(~year) +
  ggtitle("Death rate for next year (add +1 to year)")
acs_medicare_opioid_merge <- acs_medicare_opioid_merge %>% 
  mutate(id = row_number()) %>% 
  inner_join(ma_town_coord, by = c("city_death" = "town"))
set.seed(2019)
test_set_alt <- acs_medicare_opioid_merge %>% 
  sample_frac(0.2, replace = FALSE)
train_set_alt <- acs_medicare_opioid_merge %>% 
  filter(!(id %in% (test_set_alt$id)))



all_acs_model_alt <- gam(
  death_rate_per10k ~ s(x, y) + year + s(med_house_inc) + s(mean_house_inc) + s(mean_med_inc_desp) + s(drop_out) + s(less_than_hs_ed) + s(at_or_below_pov_prop) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_claim_count_avg) + s(opioid_rate_avg) + s(claim_per_65_and_over) + s(opi_claim_per_65_and_over),
  data = train_set_alt, method = "REML", select = TRUE, family = "poisson"
  )
summary(all_acs_model_alt)


mean(abs(train_set_alt$death_rate_per10k - predict(all_acs_model_alt, train_set_alt, type = "response")), na.rm = TRUE)
plot(train_set_alt$death_rate_per10k,  predict(all_acs_model_alt, train_set_alt, type = "response"))
train_set_alt$mod1_pred <- predict(all_acs_model_alt, train_set_alt, type = "response")

train_set_alt %>% 
  ggplot(aes(death_rate_per10k, mod1_pred)) +
  geom_point(alpha = 0.5, size = 1) +
  geom_abline(slope = 1, intercept = 0) +
  facet_wrap(~ year)
gam.check(all_acs_model_alt)
concurvity(all_acs_model_alt)
```




```{r}
death_acs_merge_full <- read_csv("../../../data/tidy_data/death_count_norm_to_pop_and_acs_town_demographics_merge_all_cols.csv")
benzo_pres <- read_csv("../../../data/tidy_data/med_partD_benzo_sum_w_town_merge_13_to_17.csv")
```



```{r}
acs_medicare_opioid_merge
death_acs_merge_full
```


```{r}
acs_medicare_opioid_merge <- acs_medicare_opioid_merge %>% 
  mutate(id = row_number()) %>% 
  inner_join(ma_town_coord, by = c("city_death" = "town"))
colnames(acs_medicare_opioid_merge)
table(acs_medicare_opioid_merge$year)

colnames(death_acs_merge_full)
yearly_pop <- death_acs_merge_full %>% 
  select(city_death, tot_pop_17, tot_pop_16:tot_pop_13) %>% 
  gather(key="year", value="tot_pop", -city_death) %>% 
  mutate(
    year = case_when(
      year == "tot_pop_17" ~ 2017,
      year == "tot_pop_16" ~ 2016,
      year == "tot_pop_15" ~ 2015,
      year == "tot_pop_14" ~ 2014,
      year == "tot_pop_13" ~ 2013,
      TRUE ~ 0
    )
  )

mod_df_count <- acs_medicare_opioid_merge %>% 
  select(-c(tot_pop_17, over_65_prop, mean_med_inc_desp)) %>% 
  inner_join(yearly_pop, by = c("city_death", "year"))
mod_df_count
yearly_death_count <- death_acs_merge_full %>% 
  select(city_death, `2014`:`2018`) %>% 
  gather(key="year", value="death_count_next_year", -city_death) %>% 
  mutate(year = as.numeric(year) - 1)
yearly_death_count
mod_df_count <- yearly_death_count %>% 
  inner_join(mod_df_count, by = c("city_death", "year"))
mod_df_count
benzo_pres %>% 
  ggplot(aes(sqrt(total_claim_count), sqrt(total_day_supply), color = generic_name)) +
  geom_point(alpha = 0.5, size = 1) +
  facet_wrap(~ year)
benzo_pres %>% 
  ggplot(aes(sqrt(total_claim_count), sqrt(total_30_day_fill_count), color = generic_name)) +
  geom_point(alpha = 0.5, size = 1) +
  facet_wrap(~ year)
benzo_tot_day_supp <- benzo_pres %>% 
  select(town:year, total_day_supply) %>% 
  spread(key = generic_name, value = total_day_supply)
benzo_tot_day_supp %>% 
  ggplot(aes(sqrt(alprazolam), sqrt(diazepam))) +
  geom_point() +
  facet_wrap(~ year)
benzo_tot_day_supp %>% 
  ggplot(aes(sqrt(alprazolam), sqrt(lorazepam))) +
  geom_point() +
  facet_wrap(~ year)
sapply(data.frame(sapply(benzo_tot_day_supp, is.na)), sum)
benzo_tot_day_supp_nona <- benzo_tot_day_supp %>% 
  replace(is.na(.), 0) %>% 
  rename(city_death = town)
sapply(data.frame(sapply(benzo_tot_day_supp_nona, is.na)), sum)
benzo_tot_day_supp_nona %>% 
  ggplot(aes(sqrt(alprazolam), sqrt(diazepam))) +
  geom_point() +
  facet_wrap(~ year)
benzo_tot_day_supp_nona
mod_df_count <- mod_df_count %>% 
  inner_join(benzo_tot_day_supp_nona, by = c("city_death", "year")) %>% 
  mutate(
    alprazolam_per_65_and_over = alprazolam / over_65_count,
    diazepam_per_65_and_over = diazepam / over_65_count,
    lorazepam_per_65_and_over = lorazepam / over_65_count,
    tot_benzo_count = alprazolam + diazepam + lorazepam,
    tot_benzo_per_65_and_over = tot_benzo_count / over_65_count
  )
colnames(mod_df_count)
summary(mod_df_count)
```

```{r}
library(caret)
#flds <- createFolds(y, k = 10, list = TRUE, returnTrain = FALSE)
#names(flds)[1] <- "train"
```


```{r}
set.seed(2019)
test_set_alt <- mod_df_count %>% 
  sample_frac(0.2, replace = FALSE)
train_set_alt <- mod_df_count %>% 
  filter(!(id %in% (test_set_alt$id)))
set.seed(2018)
flds <- createFolds(test_set_alt$death_count_next_year, k = 5, list = TRUE, returnTrain = FALSE)
test <- createFolds(test_set_alt$death_count_next_year, k = 5)
test_set_alt[flds[[1]], ]$id
flds[[2]]
flds[[3]]
flds[[4]]
flds[[5]]

mean(mod_df_count$death_count_next_year)
var(mod_df_count$death_count_next_year)

base_model_error <- function(fold) {
  valid_set1 <- train_set_alt[fold, ]
  train_set1 <- train_set_alt %>% filter(!(id %in% valid_set1$id))
  model1 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop),
    data = train_set1, method = "REML", family = nb()
    )
  error1 <- mean(abs(valid_set1$death_count_next_year - predict(model1, valid_set1, type = "response")))
  return(error1)
}
base_model_rmse_error <- function(fold) {
  valid_set1 <- train_set_alt[fold, ]
  train_set1 <- train_set_alt %>% filter(!(id %in% valid_set1$id))
  model1 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop),
    data = train_set1, method = "REML", family = nb()
    )
  error1 <- sqrt(mean((valid_set1$death_count_next_year - predict(model1, valid_set1, type = "response")) ^ 2))
  return(error1)
}
base_model_all_er <- map_dbl(flds, base_model_error)
base_model_all_er
mean(base_model_all_er)

base_model_all_rmse_er <- map_dbl(flds, base_model_rmse_error)
base_model_all_rmse_er
mean(base_model_all_rmse_er)

base_model <- gam(
  death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop),
  data = train_set_alt, method = "REML", family = nb()
  )
mean(abs(train_set_alt$death_count_next_year - predict(base_model, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(base_model, train_set_alt, type = "response")) ^ 2))
summary(base_model)
gam.check(base_model)
concurvity(base_model)
qq.gam(base_model)



set.seed(2017)
flds <- createFolds(test_set_alt$death_count_next_year, k = 5, list = TRUE, returnTrain = FALSE)
full_model_error <- function(fold) {
  valid_set1 <- train_set_alt[fold, ]
  train_set1 <- train_set_alt %>% filter(!(id %in% valid_set1$id))
  model1 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop) + s(med_house_inc) + s(mean_house_inc) + s(at_or_below_pov_prop) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed) + s(alprazolam_per_65_and_over) + s(diazepam_per_65_and_over) + s(lorazepam_per_65_and_over) + s(tot_benzo_per_65_and_over),
    data = train_set1, method = "REML", family = nb(), select = TRUE
    )
  error1 <- mean(abs(valid_set1$death_count_next_year - predict(model1, valid_set1, type = "response")))
  return(error1)
}
full_model_error_all_er <- map_dbl(flds, full_model_error)
full_model_error_all_er
mean(full_model_error_all_er)


full_model_rmse_error <- function(fold) {
  valid_set1 <- train_set_alt[fold, ]
  train_set1 <- train_set_alt %>% filter(!(id %in% valid_set1$id))
  model1 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop) + s(med_house_inc) + s(mean_house_inc) + s(at_or_below_pov_prop) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed) + s(alprazolam_per_65_and_over) + s(diazepam_per_65_and_over) + s(lorazepam_per_65_and_over) + s(tot_benzo_per_65_and_over),
    data = train_set1, method = "REML", family = nb(), select = TRUE
    )
  error1 <- sqrt(mean((valid_set1$death_count_next_year - predict(model1, valid_set1, type = "response")) ^ 2))
  return(error1)
}
full_model_error_all_rmse_er <- map_dbl(flds, full_model_rmse_error)
full_model_error_all_rmse_er
mean(full_model_error_all_rmse_er)

full_model <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop) + s(med_house_inc) + s(mean_house_inc) + s(at_or_below_pov_prop) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed) + s(alprazolam_per_65_and_over) + s(diazepam_per_65_and_over) + s(lorazepam_per_65_and_over) + s(tot_benzo_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model, train_set_alt, type = "response")) ^ 2))
summary(full_model)
gam.check(full_model)
concurvity(full_model)
qq.gam(full_model)

train_set_scaled <- train_set_alt %>% 
  select(-c(year:death_count_next_year, x:y)) %>% 
  mutate_if(is.numeric, scale) %>% 
    bind_cols(
      train_set_alt %>% 
        select(year:death_count_next_year, x:y)
    )
colnames(train_set_scaled)
full_model_scaled <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop) + s(med_house_inc) + s(mean_house_inc) + s(at_or_below_pov_prop) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed) + s(alprazolam_per_65_and_over) + s(diazepam_per_65_and_over) + s(lorazepam_per_65_and_over) + s(tot_benzo_per_65_and_over),
    data = train_set_scaled, method = "REML", family = nb(), select = TRUE
    )
summary(full_model_scaled)
mean(abs(train_set_scaled$death_count_next_year - predict(full_model_scaled, train_set_scaled, type = "response")))

concurvity(full_model)

full_model_sub1 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop) + s(mean_house_inc) + s(at_or_below_pov_prop) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed) + s(alprazolam_per_65_and_over) + s(diazepam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model_sub1, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model_sub1, train_set_alt, type = "response")) ^ 2))



set.seed(2016)
flds <- createFolds(test_set_alt$death_count_next_year, k = 5, list = TRUE, returnTrain = FALSE)
full_model_sub1_error <- function(fold) {
  valid_set1 <- train_set_alt[fold, ]
  train_set1 <- train_set_alt %>% filter(!(id %in% valid_set1$id))
  model1 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop) + s(mean_house_inc) + s(at_or_below_pov_prop) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed) + s(alprazolam_per_65_and_over) + s(diazepam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
  error1 <- mean(abs(valid_set1$death_count_next_year - predict(model1, valid_set1, type = "response")))
  return(error1)
}
full_model_sub1_error_all_er <- map_dbl(flds, full_model_sub1_error)
full_model_sub1_error_all_er
mean(full_model_sub1_error_all_er)

full_model_sub1_rmse_error <- function(fold) {
  valid_set1 <- train_set_alt[fold, ]
  train_set1 <- train_set_alt %>% filter(!(id %in% valid_set1$id))
  model1 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop) + s(mean_house_inc) + s(at_or_below_pov_prop) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed) + s(alprazolam_per_65_and_over) + s(diazepam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
  error1 <- sqrt(mean((valid_set1$death_count_next_year - predict(model1, valid_set1, type = "response")) ^ 2))
  return(error1)
}
full_model_sub1_error_all_rmse_er <- map_dbl(flds, full_model_sub1_rmse_error)
full_model_sub1_error_all_rmse_er
mean(full_model_sub1_error_all_rmse_er)

summary(full_model_sub1)
gam.check(full_model_sub1)
concurvity(full_model_sub1)
qq.gam(full_model_sub1)

full_model_sub1_conc <- concurvity(full_model_sub1, full = FALSE) %>%
  data.frame() %>% 
  rownames_to_column("feature") %>% 
  tbl_df() %>% 
  mutate_if(is.numeric, round, 3) %>% 
  select(feature, contains("worst"))
full_model_sub1_conc
full_model_sub1_conc %>% 
  select(feature, contains("tot_pop"))
full_model_sub1_conc %>% 
  select(feature, contains("at_or_below_pov"))

# take out below poverty feature
full_model_sub2 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop) + s(mean_house_inc) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed) + s(alprazolam_per_65_and_over) + s(diazepam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model_sub2, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model_sub2, train_set_alt, type = "response")) ^ 2))
summary(full_model_sub2)
gam.check(full_model_sub2)
qq.gam(full_model_sub2, cex=3)
concurvity(full_model_sub2)

#ti(Longitude, Latitude, Year, d=c(2,1))

full_model_sub3 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + ti(x, y, year, d=c(2, 1))+ s(tot_pop) + s(mean_house_inc) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed) + s(alprazolam_per_65_and_over) + s(diazepam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model_sub3, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model_sub3, train_set_alt, type = "response")) ^ 2))
summary(full_model_sub3)
gam.check(full_model_sub3)
qq.gam(full_model_sub3, cex=3)
concurvity(full_model_sub3)


full_model_sub4 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + ti(x, y, tot_pop, d=c(2, 1))+ s(tot_pop) + s(mean_house_inc) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed) + s(alprazolam_per_65_and_over) + s(diazepam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model_sub4, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model_sub4, train_set_alt, type = "response")) ^ 2))
summary(full_model_sub4)
gam.check(full_model_sub4)
qq.gam(full_model_sub4, cex=3)
concurvity(full_model_sub4)

full_model_sub4_conc <- concurvity(full_model_sub4, full = FALSE) %>%
  data.frame() %>% 
  rownames_to_column("feature") %>% 
  tbl_df() %>% 
  mutate_if(is.numeric, round, 3) %>% 
  select(feature, contains("worst"))
full_model_sub4_conc
full_model_sub4_conc %>% 
  select(feature, contains("tot_pop"))
full_model_sub4_conc %>% 
  select(feature, contains("mean_house_inc"))
full_model_sub4_conc %>% 
  select(feature, contains("per_65_and_over"))
train_set_alt %>% 
  ggplot(aes(diazepam_per_65_and_over, lorazepam_per_65_and_over)) +
  geom_point()


full_model_sub5 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + ti(x, y, tot_pop, d=c(2, 1))+ s(tot_pop) + s(mean_house_inc) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model_sub5, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model_sub5, train_set_alt, type = "response")) ^ 2))
summary(full_model_sub5)
gam.check(full_model_sub5)
qq.gam(full_model_sub5, cex=3)
concurvity(full_model_sub5)


full_model_sub6 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + ti(x, y, tot_pop, d=c(2, 1))+ s(tot_pop) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model_sub6, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model_sub6, train_set_alt, type = "response")) ^ 2))
summary(full_model_sub6)
gam.check(full_model_sub6)
qq.gam(full_model_sub6, cex=3)
concurvity(full_model_sub6)


set.seed(2000)
flds <- createFolds(test_set_alt$death_count_next_year, k = 5, list = TRUE, returnTrain = FALSE)
full_model_sub6_rmse_error <- function(fold) {
  valid_set1 <- train_set_alt[fold, ]
  train_set1 <- train_set_alt %>% filter(!(id %in% valid_set1$id))
  model1 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + ti(x, y, tot_pop, d=c(2, 1))+ s(tot_pop) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
  error1 <- sqrt(mean((valid_set1$death_count_next_year - predict(model1, valid_set1, type = "response")) ^ 2))
  return(error1)
}
full_model_sub6_error_all_rmse_er <- map_dbl(flds, full_model_sub6_rmse_error)
full_model_sub6_error_all_rmse_er
mean(full_model_sub6_error_all_rmse_er)


full_model_sub7 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + ti(x, y, tot_pop, d=c(2, 1))+ s(tot_pop) + s(pop_struggling_prop, k=12) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed, k=12) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model_sub7, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model_sub7, train_set_alt, type = "response")) ^ 2))
summary(full_model_sub7)
gam.check(full_model_sub7)
qq.gam(full_model_sub7, cex=3)
concurvity(full_model_sub7)


full_model_sub8 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + ti(x, y, tot_pop, d=c(2, 1))+ s(tot_pop) + s(pop_struggling_prop, k=20) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed, k=20) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model_sub8, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model_sub8, train_set_alt, type = "response")) ^ 2))
summary(full_model_sub8)
gam.check(full_model_sub8)
qq.gam(full_model_sub8, cex=3)
concurvity(full_model_sub8)


set.seed(1999)
flds <- createFolds(test_set_alt$death_count_next_year, k = 5, list = TRUE, returnTrain = FALSE)
full_model_sub8_rmse_error <- function(fold) {
  valid_set1 <- train_set_alt[fold, ]
  train_set1 <- train_set_alt %>% filter(!(id %in% valid_set1$id))
  model1 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + ti(x, y, tot_pop, d=c(2, 1))+ s(tot_pop) + s(pop_struggling_prop, k=20) + town_status + urb_v_rur + s(opioid_rate_avg) + s(less_than_hs_ed, k=20) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
  error1 <- sqrt(mean((valid_set1$death_count_next_year - predict(model1, valid_set1, type = "response")) ^ 2))
  return(error1)
}
full_model_sub8_error_all_rmse_er <- map_dbl(flds, full_model_sub8_rmse_error)
full_model_sub8_error_all_rmse_er
mean(full_model_sub8_error_all_rmse_er)


full_model_sub8_conc <- concurvity(full_model_sub8, full = FALSE) %>%
  data.frame() %>% 
  rownames_to_column("feature") %>% 
  tbl_df() %>% 
  mutate_if(is.numeric, round, 3) %>% 
  select(feature, contains("worst"))

full_model_sub8_conc %>% 
  gather(key="feature2", value="value", -feature) %>% 
  ggplot(aes(feature, feature2, fill=value)) +
  geom_raster() +
  scale_fill_viridis_c() +
  theme(axis.text.x = element_text(angle=90))


full_model_sub8_conc
full_model_sub8_conc %>% 
  select(feature, contains("hs_ed"))
train_set_alt %>% 
  ggplot(aes(pop_struggling_prop, less_than_hs_ed)) +
  geom_point()



full_model_sub9 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + ti(x, y, tot_pop, d=c(2, 1))+ s(tot_pop) + s(pop_struggling_prop) + town_status + urb_v_rur + s(opioid_rate_avg) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model_sub9, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model_sub9, train_set_alt, type = "response")) ^ 2))
summary(full_model_sub9)
gam.check(full_model_sub9)
qq.gam(full_model_sub9, cex=3)
concurvity(full_model_sub9)


full_model_sub10 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + ti(x, y, tot_pop, d=c(2, 1))+ s(tot_pop) + s(pop_struggling_prop) + town_status + s(opioid_rate_avg) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model_sub10, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model_sub10, train_set_alt, type = "response")) ^ 2))
summary(full_model_sub10)
gam.check(full_model_sub10)
qq.gam(full_model_sub10, cex=3)
concurvity(full_model_sub10)


full_model_sub10_conc <- concurvity(full_model_sub10, full = FALSE) %>%
  data.frame() %>% 
  rownames_to_column("feature") %>% 
  tbl_df() %>% 
  mutate_if(is.numeric, round, 3) %>% 
  select(feature, contains("worst"))
full_model_sub10_conc %>% 
  select(feature, contains("tot_pop"))


full_model_sub11 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop) + s(pop_struggling_prop) + town_status + s(opioid_rate_avg) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model_sub11, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model_sub11, train_set_alt, type = "response")) ^ 2))
summary(full_model_sub11)
gam.check(full_model_sub11)
qq.gam(full_model_sub11, cex=3)
concurvity(full_model_sub11)

#less_than_hs_ed
full_model_sub12 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop) + s(pop_struggling_prop) + town_status + s(opioid_rate_avg) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over) +s(less_than_hs_ed),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model_sub12, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model_sub12, train_set_alt, type = "response")) ^ 2))
summary(full_model_sub12)
gam.check(full_model_sub12)
qq.gam(full_model_sub12, cex=3)
concurvity(full_model_sub12)


set.seed(1998)
flds <- createFolds(test_set_alt$death_count_next_year, k = 5, list = TRUE, returnTrain = FALSE)
full_model_sub11_rmse_error <- function(fold) {
  valid_set1 <- train_set_alt[fold, ]
  train_set1 <- train_set_alt %>% filter(!(id %in% valid_set1$id))
  model1 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop) + s(pop_struggling_prop) + town_status + s(opioid_rate_avg) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
  error1 <- sqrt(mean((valid_set1$death_count_next_year - predict(model1, valid_set1, type = "response")) ^ 2))
  return(error1)
}
full_model_sub11_error_all_rmse_er <- map_dbl(flds, full_model_sub11_rmse_error)
full_model_sub11_error_all_rmse_er
mean(full_model_sub11_error_all_rmse_er)


set.seed(1997)
flds <- createFolds(test_set_alt$death_count_next_year, k = 5, list = TRUE, returnTrain = FALSE)
full_model_sub12_rmse_error <- function(fold) {
  valid_set1 <- train_set_alt[fold, ]
  train_set1 <- train_set_alt %>% filter(!(id %in% valid_set1$id))
  model1 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop) + s(pop_struggling_prop) + town_status + s(opioid_rate_avg) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over) +s(less_than_hs_ed),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
  error1 <- sqrt(mean((valid_set1$death_count_next_year - predict(model1, valid_set1, type = "response")) ^ 2))
  return(error1)
}
full_model_sub12_error_all_rmse_er <- map_dbl(flds, full_model_sub12_rmse_error)
full_model_sub12_error_all_rmse_er
mean(full_model_sub12_error_all_rmse_er)



full_model_sub13 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop, k=12) + s(pop_struggling_prop, k = 15) + town_status + s(opioid_rate_avg, k = 12) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
mean(abs(train_set_alt$death_count_next_year - predict(full_model_sub13, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(full_model_sub13, train_set_alt, type = "response")) ^ 2))
summary(full_model_sub13)
gam.check(full_model_sub13)
qq.gam(full_model_sub13, cex=3)
concurvity(full_model_sub13)


set.seed(1996)
flds <- createFolds(test_set_alt$death_count_next_year, k = 5, list = TRUE, returnTrain = FALSE)
full_model_sub13_rmse_error <- function(fold) {
  valid_set1 <- train_set_alt[fold, ]
  train_set1 <- train_set_alt %>% filter(!(id %in% valid_set1$id))
  model1 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop, k=12) + s(pop_struggling_prop, k = 15) + town_status + s(opioid_rate_avg, k = 12) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
  error1 <- sqrt(mean((valid_set1$death_count_next_year - predict(model1, valid_set1, type = "response")) ^ 2))
  return(error1)
}
full_model_sub13_error_all_rmse_er <- map_dbl(flds, full_model_sub13_rmse_error)
full_model_sub13_error_all_rmse_er
mean(full_model_sub13_error_all_rmse_er)

set.seed(1996)
flds <- createFolds(test_set_alt$death_count_next_year, k = 5, list = TRUE, returnTrain = FALSE)
full_model_sub13_mae_error <- function(fold) {
  valid_set1 <- train_set_alt[fold, ]
  train_set1 <- train_set_alt %>% filter(!(id %in% valid_set1$id))
  model1 <- gam(
    death_count_next_year ~ s(x,y) + s(year, k=3) + s(tot_pop, k=12) + s(pop_struggling_prop, k = 15) + town_status + s(opioid_rate_avg, k = 12) + s(alprazolam_per_65_and_over) + s(lorazepam_per_65_and_over),
    data = train_set_alt, method = "REML", family = nb(), select = TRUE
    )
  error1 <- mean(abs(valid_set1$death_count_next_year - predict(model1, valid_set1, type = "response")))
  return(error1)
}
full_model_sub13_error_all_mae_er <- map_dbl(flds, full_model_sub13_mae_error)
full_model_sub13_error_all_mae_er
mean(full_model_sub13_error_all_mae_er)


final_model <- full_model_sub13
mean(abs(train_set_alt$death_count_next_year - predict(final_model, train_set_alt, type = "response")))
sqrt(mean((train_set_alt$death_count_next_year - predict(final_model, train_set_alt, type = "response")) ^ 2))
summary(final_model)
gam.check(final_model)
qq.gam(final_model, cex=3)
concurvity(final_model)

mean(abs(test_set_alt$death_count_next_year - predict(final_model, test_set_alt, type = "response")))
sqrt(mean((test_set_alt$death_count_next_year - predict(final_model, test_set_alt, type = "response")) ^ 2))
sd(test_set_alt$death_count_next_year)
mean(test_set_alt$death_count_next_year)
mod_df_count$fin_pred <- predict(final_model, mod_df_count, type = "response")


library(mgcViz)
test <- getViz(final_model)
qq(test, rep = 10, method = "simul1", CI = "normal", showReps = TRUE,
        ngr = 1e2, a.replin = list(alpha = 0.1), a.qqpoi = list(shape = 19)) +
  ggtitle("QQ Plot\nNegative binomial GAM") +
  xlab("Theoretical Quantiles") +
  ylab("Deviance Residuals") +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 14)
    )
library(broom)
tidy(final_model)
tidy(final_model, parametric=TRUE)
coef(final_model)



print(plot(test, allTerms = T), pages = 1)
```


```{r}
mod_df_count

mod_df_count %>% 
  mutate(year = as_factor(year+1)) %>% 
  ggplot(aes(death_count_next_year, fill = year)) +
  geom_histogram(position="dodge", bins=10) +
  scale_fill_brewer(type = "seq", name = "Year", direction = -1) + 
  theme_dark() +
  xlab("Number of Overdose Deaths per Town") +
  ylab("Count") +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 14)
    )
library(ggridges)
mod_df_count %>% 
  mutate(year = fct_rev(as_factor(year+1))) %>% 
  ggplot(aes(death_count_next_year, y = year, fill = year)) +
  geom_density_ridges(stat = "binline", binwidth=5,draw_baseline = F) +
  theme_ridges() +
  scale_y_discrete(expand = c(0.01, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_fill_brewer(type = "seq", name = "Year") +
  xlab("Number of opioid overdose deaths per town") +
  ylab("Year")

mod_df_count %>% 
  filter(year == 2017) %>% 
  mutate(year = fct_rev(as_factor(year+1))) %>% 
  ggplot(aes(death_count_next_year)) +
  geom_histogram(binwidth = 5) +
  xlab("Number of Overdose Deaths per Town") +
  ylab("Count") +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 14)
    )


ma_total_deaths <- read_csv("../../../data/tidy_data/ma_total_overdose_for_graph.csv")
ma_total_deaths %>% 
  ggplot(aes(year, overdose_deaths, fill = group)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values=c("grey80", "orange2"), guide=FALSE) +
  ylab("Number of Deaths") +
  xlab("Year") +
  ggtitle("Opioid-related deaths for the state of Massachusetts") +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 14),
    plot.title = element_text(size = 16)
    ) +
  scale_x_continuous(breaks=c(2000, 2014, 2018))


#nyc.census.4boro %>% 
#  ggplot() +
#  geom_sf(color = "#BFBFBF") +
#  geom_sf(data = tract.cent, size = 0.75, color = "#4E79A7") +
#  ggtitle("NYC census tract centroids") + 
#  theme(axis.text.x = element_blank(), axis.text.y = element_blank())

ma_town_centroids <- st_centroid(ma_town_map_w_data)
ma_town_map_w_data %>% 
  ggplot() +
  geom_sf(color = "grey80") +
  geom_sf(data = ma_town_centroids, size = 2, color = "orange2") +
  theme(axis.text.x = element_blank(), axis.text.y = element_blank())


mod_df_count %>% 
  mutate(year = year+1) %>% 
  ggplot(aes(death_count_next_year, fin_pred)) +
  geom_point(size=2, alpha=0.5) +
  geom_smooth(method="lm", se=FALSE, size = 1.5) +
  geom_abline(intercept = 0, slope = 1, color="orange2", size = 1.5) +
  scale_y_sqrt(limits=c(0,300)) +
  scale_x_sqrt(limits=c(0,300)) +
  ylab("Predicted Count")+
  xlab("Actual Count") +
  ggtitle("Predicted vs Actual Opioid Overdose Death Counts\n(sqrt scale)") +
  theme(
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14),
    axis.title = element_text(size = 16),
    plot.title = element_text(size = 18)
    )
mod_df_count$resid <- mod_df_count$death_count_next_year - mod_df_count$fin_pred
mod_df_count %>% 
  ggplot(aes(death_count_next_year, resid)) +
  geom_point(alpha = 0.5) +
  facet_wrap(~year) +
  geom_hline(yintercept = 0) +
  scale_x_sqrt() +
  xlab("Overdose death count") +
  ylab("Residual")
mod_df_death_rate <- mod_df_count %>% 
  mutate(year=year+1) %>% 
  select(city_death:death_count_next_year, fin_pred, tot_pop) %>% 
  mutate(
    actual_death_rate = death_count_next_year * 10000/ tot_pop,
    pred_death_rate = fin_pred * 10000/ tot_pop
  )
mod_df_death_rate %>% 
  ggplot(aes(year, pred_death_rate, group = city_death)) +
  geom_line(alpha = 0.5)
mod_df_death_rate %>% 
  ggplot(aes(year, actual_death_rate, group = city_death)) +
  geom_line(alpha = 0.5)
mod_df_death_rate %>% 
  arrange(desc(pred_death_rate))
mod_df_death_rate %>% 
  select(city_death:year, actual_death_rate:pred_death_rate) %>% 
  gather(key="measure", value="value", actual_death_rate:pred_death_rate) %>% 
  mutate(measure = ifelse(measure=="actual_death_rate", "Actual Death Rate", "Predicted Death Rate")) %>% 
  ggplot(aes(year, value, group = city_death)) +
  geom_line(alpha = 0.5) +
  facet_wrap(~measure) +
  xlab("Year") +
  ylab("Rate per 10k residents") +
  theme(
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14),
    axis.title = element_text(size = 16),
    plot.title = element_text(size = 18),
    strip.text.x = element_text(size=14) 
    ) +
  ggtitle("Actual and Predicted Opioid Overdose Deaths by MA Town\nDeath rate per 10k town residents")

mod_df_death_rate %>% 
  filter(year == 2016) %>% 
  arrange(desc(pred_death_rate))
mod_df_death_rate %>% 
  filter(year == 2018) %>% 
  arrange(desc(pred_death_rate))
```

