---
title: "Maps and other figures"
author: "darya akimova"
date: "10/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

## Packages:

```{r packages, comment=NA}
library(tidyverse)
library(ggridges)
library(cowplot)
library(viridis)
library(ggthemes)
library(sf)
theme_set(theme_minimal())
```


## Data:

```{r data_import, comment=NA}
death_and_acs_data <- read_csv("../../data/tidy_data/overdose_death_count_acs_merge_long_format.csv")
ma_total_deaths <- read_csv("../../data/tidy_data/ma_total_overdose_for_graph.csv")
mod_df_count <- read_csv("../../data/tidy_data/final_model_df_with_features_and_pred.csv")
ma_town_map <- st_read("../../data/raw_data/shapefiles_and_geography_related/townssurvey_shp/TOWNSSURVEY_POLYM.shp")
death_and_acs_wide <- read_csv("../../data/tidy_data/overdose_death_count_acs_merge.csv")
```


# Plots

```{r ma_total_deaths_plot}
# for presentation
ma_total_deaths %>% 
  ggplot(aes(year, overdose_deaths, fill = group)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values=c("grey80", "orange2"), guide=FALSE) +
  ylab("") +
  xlab("Year") +
  ggtitle("Total opioid-related deaths per year\nMassachusetts") +
  theme(
    axis.text.x = element_text(size = 24),
    axis.text.y = element_text(size = 24),
    axis.title = element_text(size = 24),
    plot.title = element_text(size = 24)
    ) +
  scale_x_continuous(breaks=c(2000, 2014, 2018))
# for blog
ma_total_deaths_for_blog <- ma_total_deaths %>% 
  ggplot(aes(year, overdose_deaths, fill = group)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values=c("grey80", "orange2"), guide=FALSE) +
  ylab("Number of Deaths") +
  xlab("Year") +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 14),
    plot.title = element_text(size = 16)
    ) +
  ggtitle("Total opioid overdose death per year\nMassachusetts") +
  scale_x_continuous(breaks=c(2002, 2006,2010, 2014, 2018))
ma_total_deaths_for_blog
#save_plot("../../figures/tidy_figures/ma_deaths_for_blog.png", ma_total_deaths_for_blog, base_width = 8, base_height=4)
```




```{r opioid_overdose_death_rate_maps}
ma_town_map_w_data <- ma_town_map %>% 
  st_transform(crs = "+init=epsg:4326") %>% 
  mutate(TOWN = str_to_lower(TOWN)) %>% 
  left_join(death_and_acs_data, by = c("TOWN" = "city_death"))
```



```{r some_feature_maps}
ma_town_map_w_data %>% 
  mutate(
    town_status = replace_na(town_status, "missing"),
    town_status = as_factor(town_status)
  ) %>% 
  filter(year == 2017) %>% 
  ggplot() +
  geom_sf(aes(fill = town_status)) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.major = element_line(colour = 'transparent'),
    legend.text = element_text(size = 20),
    plot.title = element_text(size = 24)
    ) +
  scale_fill_manual(values= c("#1b9e77", "#d95f02", "#7570b3", "#e7298a"), name  = NULL) +
  ggtitle("Town Pop Grown/Shrunk (2010 - 2017)")
ma_town_map_w_data %>% 
  filter(year == 2017) %>% 
  ggplot() +
  geom_sf(aes(fill = log(tot_pop + 1))) +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.major = element_line(colour = 'transparent'),
    legend.text = element_text(size = 20),
    plot.title = element_text(size = 24)
    ) +
  scale_fill_viridis_c(option="D", name = NULL) +
  ggtitle("2017 Town Population\nlog scale")
```



```{r}
mod_df_count %>% 
  mutate(year = as_factor(year+1)) %>% 
  ggplot(aes(death_count_next_year, fill = year)) +
  geom_histogram(position="dodge", bins=10) +
  scale_fill_brewer(type = "seq", name = "Year", direction = -1) + 
  theme_dark() +
  xlab("Number of Overdose Deaths per Town") +
  ylab("Count") +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 14)
    )

mod_df_count %>% 
  mutate(year = fct_rev(as_factor(year+1))) %>% 
  ggplot(aes(death_count_next_year, y = year, fill = year)) +
  geom_density_ridges(stat = "binline", binwidth=5,draw_baseline = F) +
  theme_ridges() +
  scale_y_discrete(expand = c(0.01, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_fill_brewer(type = "seq", name = "Year") +
  xlab("Number of opioid overdose deaths per town") +
  ylab("") +
  theme(
    axis.text.x = element_text(size = 24),
    axis.text.y = element_text(size = 24),
    axis.title = element_text(size = 24),
    legend.text = element_text(size = 24),
    legend.title = element_text(size = 24)
    )

mod_df_count %>% 
  filter(year == 2017) %>% 
  mutate(year = fct_rev(as_factor(year+1))) %>% 
  ggplot(aes(death_count_next_year)) +
  geom_histogram(binwidth = 5) +
  xlab("") +
  ylab("") +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 14)
    )



ma_town_centroids <- st_centroid(ma_town_map_w_data)
ma_map_with_towns_and_centroids <- ma_town_map_w_data %>% 
  ggplot() +
  geom_sf(color = "grey20") +
  geom_sf(data = ma_town_centroids, size = 1.5, color = "#d95f02") +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.major = element_line(colour = 'transparent')
    ) +
  ggtitle("Massachusetts municipal (city and town) boundaries\nCentroids overlaid")
ma_map_with_towns_and_centroids


ma_town_map_w_data %>%
  filter(year == 2017) %>% 
  ggplot() +
  geom_sf(aes(fill = death_count_next_year), color = "black") +
  scale_fill_viridis_c(option = "D", name = "Count") +
  theme(axis.text.x = element_blank(), axis.text.y = element_blank()) +
  ggtitle("Opioid overdose death counts per town\n2018")

ma_overdose_death_cut <- ma_town_map_w_data %>%
  filter(year == 2017)

ma_overdose_death_cut$death_count_next_year <- cut(ma_overdose_death_cut$death_count_next_year, breaks = c(0, 1, 5, 10, 50, 250), include.lowest = TRUE)
table(ma_overdose_death_cut$death_count_next_year)
ma_map_2018_count <- ma_overdose_death_cut %>%
  ggplot() +
  geom_sf(aes(fill = death_count_next_year), color = "gray50") +
  scale_fill_viridis_d(option = "D", name = "Count\nInterval") +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.major = element_line(colour = 'transparent'),
    plot.title = element_text(size = 22),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 18)
    ) +
  ggtitle("Opioid overdose death counts per town per year\n2018")
ma_map_2018_count 
#save_plot(
#  filename= "../../figures/tidy_figures/ma_towns_map_and_deaths_2018.png",
#  ma_map_2018_count,
#  base_height = 5,
#  base_width = 10
#  )


death_count_year_hist <- mod_df_count %>% 
  mutate(year = fct_rev(as_factor(year + 1))) %>% 
  ggplot(aes(death_count_next_year, y = year, fill = year)) +
  geom_density_ridges(stat = "binline", binwidth = 5, draw_baseline = F) +
  theme_ridges() +
  scale_y_discrete(expand = c(0.01, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_fill_brewer(type = "seq", name = "Year") +
  xlab("Number of opioid overdose deaths per town") +
  ylab("Year") +
  ggtitle("Opioid overdose death counts distributions")
death_count_year_hist


predicted_vs_actual_plot_all_years <- mod_df_count %>% 
  mutate(year = year + 1) %>% 
  ggplot(aes(death_count_next_year, fin_pred)) +
  geom_point(size = 2, alpha = 0.5) +
  geom_smooth(method="lm", se = FALSE, size = 1.5) +
  scale_y_sqrt(limits=c(0, 300)) +
  scale_x_sqrt(limits=c(0, 300)) +
  ylab("Predicted")+
  xlab("Actual") +
  ggtitle("Predicted vs Actual Opioid Overdose Death Counts\nsquare root scale") +
  theme(
    axis.text.x = element_text(size = 20),
    axis.text.y = element_text(size = 20),
    axis.title = element_text(size = 20),
    plot.title = element_text(size = 24)
    )
predicted_vs_actual_plot_all_years
#save_plot(
#  filename= "../../figures/tidy_figures/predicted_vs_actual_plot_all_years.png",
#  predicted_vs_actual_plot_all_years,
#  base_height = 8,
#  base_width = 10
#  )
mod_df_count %>% 
  mutate(year = year + 1) %>% 
  ggplot(aes(death_count_next_year, fin_pred)) +
  geom_point(size = 2, alpha = 0.5) +
  geom_smooth(method="lm", se = FALSE, size = 1.5) +
  scale_y_sqrt(limits=c(0, 300)) +
  scale_x_sqrt(limits=c(0, 300)) +
  ylab("Predicted")+
  xlab("Actual") +
  ggtitle("Predicted vs Actual Opioid Overdose Death Counts\nsquare root scale") +
  facet_wrap(~ year)
mod_df_count$resid <- mod_df_count$death_count_next_year - mod_df_count$fin_pred
residuals_plot_sep_years <- mod_df_count %>% 
  ggplot(aes(death_count_next_year, resid)) +
  geom_point(alpha = 0.5) +
  facet_wrap(~year) +
  geom_hline(yintercept = 0) +
  scale_x_sqrt() +
  xlab("Overdose death count") +
  ylab("Residual") +
  theme(
    axis.text.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    axis.title = element_text(size = 16),
    strip.text.x = element_text(size=16) 
    )
residuals_plot_sep_years 
#save_plot(
#  filename= "../../figures/tidy_figures/model_residuals_plot_sep_years.png",
#  residuals_plot_sep_years,
#  base_height = 8,
#  base_width = 12
#  )
```


```{r death_rate_comparison_fig}
mod_df_death_rate <- mod_df_count %>% 
  mutate(year=year+1) %>% 
  select(city_death:death_count_next_year, fin_pred, tot_pop) %>% 
  mutate(
    actual_death_rate = death_count_next_year * 10000/ tot_pop,
    pred_death_rate = fin_pred * 10000/ tot_pop,
    town_col = case_when(
      city_death == "ayer" ~ "Ayer",
      city_death == "gardner" ~ "Gardner",
      city_death == "worcester" ~ "Worcester",
      city_death == "fall river" ~ "Fall River",
      TRUE ~ "Other"
    ),
    town_shape = ifelse(city_death %in% c("ayer", "gardner", "worcester", "fall river"), 1.5, 0.5)
  )


mod_df_death_rate %>% 
  arrange(desc(actual_death_rate))
mod_df_death_rate %>% 
  filter(year == 2018) %>% 
  arrange(desc(pred_death_rate))
mod_df_death_rate_gath <- mod_df_death_rate %>% 
  select(city_death:year, actual_death_rate:pred_death_rate, town_col) %>% 
  gather(key="measure", value="value", actual_death_rate:pred_death_rate) %>% 
  mutate(measure = ifelse(measure=="actual_death_rate", "Actual", "Predicted")) 
death_rate_comp_plot <- mod_df_death_rate_gath %>% 
  filter(town_col == "Other") %>% 
  ggplot(aes(year, value, group = city_death, color = town_col)) +
  geom_line(alpha = 0.5) +
  geom_line(
    data = mod_df_death_rate_gath %>% filter(town_col != "Other"),
    aes(year, value, group = city_death, color = town_col),
    size = 2.5
    ) +
  facet_wrap(~measure) +
  xlab("Year") +
  ylab("") +
  theme(
    axis.text.x = element_text(size = 20),
    axis.text.y = element_text(size = 20),
    axis.title = element_text(size = 20),
    plot.title = element_text(size = 22),
    strip.text.x = element_text(size = 20),
    legend.text = element_text(size = 20),
    legend.title = element_text(size = 20)
    ) +
  ggtitle("Actual v Predicted opioid overdose death rate per town\nRate per 10k town residents") +
  scale_color_manual(values = c("#1b9e77", "#d95f02",  "#7570b3", "grey50","#e7298a"), name = "Towns")
death_rate_comp_plot
#save_plot(
#  filename= "../../figures/tidy_figures/actual_and_pred_deathrate_comp.png",
#  death_rate_comp_plot,
#  base_height = 8,
#  base_width = 16
#  )
```


## For EB Smoothing


```{r}
death_rates_and_prop <- death_and_acs_wide %>% 
  mutate(
    tot_pop_18 = tot_pop_17 + (tot_pop_17 - tot_pop_16),
    death_rate_14 = (`2014` / tot_pop_14) * 10000,
    death_rate_15 = (`2015` / tot_pop_15) * 10000,
    death_rate_16 = (`2016` / tot_pop_16) * 10000,
    death_rate_17 = (`2017` / tot_pop_17) * 10000,
    death_rate_18 = (`2018` / tot_pop_18) * 10000
    ) %>% 
  select(city_death, starts_with("death_rate"), over_65_prop, less_than_hs_ed, at_or_below_pov_prop, pop_struggling_prop)
death_rates_and_prop
ma_town_map %>% 
  anti_join(
    death_rates_and_prop %>% 
      mutate(city_death = str_to_upper(city_death)),
     by = c("TOWN" = "city_death")
  )
death_rates_and_prop %>% 
  mutate(city_death = str_to_upper(city_death)) %>% 
  anti_join(ma_town_map, by = c("city_death" = "TOWN"))
death_rates_and_prop <- death_rates_and_prop %>% 
  mutate(city_death = str_to_upper(city_death))
death_rates_and_prop
#write_csv(death_rates_and_prop, "../../data/tidy_data/death_rates_for_EB_smooth.csv")
death_counts_for_eb_smooth <- death_and_acs_wide %>% 
  mutate(
    tot_pop_18 = tot_pop_17 + (tot_pop_17 - tot_pop_16),
    city_death = str_to_upper(city_death)
  ) %>% 
  select(city_death:tot_pop_17, tot_pop_18) %>% 
  select(-tot_pop_13)
death_counts_for_eb_smooth
#write_csv(death_counts_for_eb_smooth, "../../data/tidy_data/death_counts_for_EB_smooth.csv")
```


Results of smoothing:

```{r}
ma_town_map <- st_read("../../data/raw_data/shapefiles_and_geography_related/townssurvey_shp/TOWNSSURVEY_POLYM.shp")
eb_smooth_rates <- read_csv("../../data/tidy_data/eb_smooth_data/EB_smoothed_death_rates.csv") %>% 
  select(TOWN, `2014`:EB_rate_18)
rate_ma_town_map <- ma_town_map %>% 
  select(-c(POP1980:POPCH90_00, POP2010:POPCH00_10)) %>% 
  mutate(
    raw_rate_2014 = X2014 * 10000 / tot_pop_14,
    raw_rate_2015 = X2015 * 10000 / tot_pop_15,
    raw_rate_2016 = X2016 * 10000 / tot_pop_16,
    raw_rate_2017 = X2017 * 10000 / tot_pop_17,
    raw_rate_2018 = X2018 * 10000 / tot_pop_18
    ) %>% 
  select(-c(X2014:tot_pop_18)) %>% 
  mutate(TOWN = str_to_lower(TOWN)) %>% 
  mutate(
    EB_rate_14 = EB_rate_14 * 10000,
    EB_rate_15 = EB_rate_15 * 10000,
    EB_rate_16 = EB_rate_16 * 10000,
    EB_rate_17 = EB_rate_17 * 10000,
    EB_rate_18 = EB_rate_18 * 10000
  )
rate_ma_town_map



#eb_smooth_rates
#map_eb_rates <- ma_town_map %>% 
#  inner_join(eb_smooth_rates, by = "TOWN") %>% 
#  mutate_at(vars(matches("EB_rate")), function(x) x * 10000) 
rate_ma_town_map %>%
  ggplot() +
  geom_sf(aes(fill = raw_rate_2018), color = "black") +
  scale_fill_viridis_c(option = "D", name = "Count") +
  theme(axis.text.x = element_blank(), axis.text.y = element_blank()) +
  ggtitle("Opioid overdose death rate per 10k residents\n2018 - Raw")
rate_ma_town_map %>%
  ggplot() +
  geom_sf(aes(fill = EB_rate_18), color = "black") +
  scale_fill_viridis_c(option = "D", name = "Count") +
  theme(axis.text.x = element_blank(), axis.text.y = element_blank()) +
  ggtitle("Opioid overdose death rate per 10k residents\n2018 - EB Smoothed")


rates_df <- rate_ma_town_map %>% 
  select(TOWN, EB_rate_14:raw_rate_2018)
st_geometry(rates_df) <- NULL
rates_df_long <- rates_df %>% 
  as_tibble() %>% 
  pivot_longer(EB_rate_14:raw_rate_2018, names_to = "type_year", values_to = "rate_per_10k") %>% 
  mutate(
    rate_type = ifelse(str_detect(type_year, "EB"), "EB", "raw"),
    year = ifelse(
      str_detect(type_year, "14"), 2014,
      ifelse(
        str_detect(type_year, "15"), 2015,
        ifelse(
          str_detect(type_year, "16"), 2016,
          ifelse(
            str_detect(type_year, "17"), 2017, 2018)
        )))
  ) %>% 
  select(-type_year)
rates_df_long %>% 
  ggplot(aes(rate_per_10k, fill = rate_type)) +
  geom_density(alpha = 0.8) +
  facet_wrap(~ year)
rates_df_long %>% 
  ggplot(aes(x = rate_type, y = rate_per_10k, fill = rate_type)) +
  geom_boxplot() +
  facet_wrap(~ year) +
  scale_fill_tableau()

data_summary <- function(x) {
   m <- mean(x)
   ymin <- m - sd(x)
   ymax <- m + sd(x)
   return(c(y = m, ymin = ymin, ymax = ymax))
}

death_rates_raw_v_eb_plot <- rates_df_long %>% 
  mutate(
    rate_type = as.factor(rate_type),
    rate_type = fct_relevel(rate_type, "raw") 
    ) %>% 
  ggplot(aes(x = rate_type, y = rate_per_10k, fill = rate_type, color = rate_type)) +
  geom_violin() +
  stat_summary(fun.data = data_summary, color = "black", alpha = 0.8) +
  facet_wrap(~ year) +
  scale_fill_tableau() +
  scale_color_tableau() +
  xlab("Rate Type") +
  theme(
    legend.position = "none",
    axis.text.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    axis.title = element_text(size = 16),
    plot.title = element_text(size = 18),
    strip.text.x = element_text(size = 16),
    plot.subtitle = element_text(size = 14),
    plot.caption = element_text(size = 12)
    ) +
  ylab("Rate per 10k town residents") +
  labs(
    title = "Opioid overdose death rates per 10k MA town residents",
    subtitle = "Raw vs EB-smoothed, by year",
    caption = "Error bar = SD"
    )
death_rates_raw_v_eb_plot
#save_plot(
#  filename= "../../figures/tidy_figures/raw_vs_eb_smoothed_death_rates.png",
#  death_rates_raw_v_eb_plot,
#  base_height = 6,
#  base_width = 12
#  )

updated_model_df <- read_csv("../../data/tidy_data/eb_smooth_final_model_df_with_features_and_pred.csv")
updated_model_df
mod_df_count

drug_counts_for_smooth <- read_csv("../../data/tidy_data/eb_smooth_data/drug_counts_for_eb_smooth.csv")


map_w_benzo_pres <- rate_ma_town_map %>%
  left_join(
    drug_counts_for_smooth %>% 
      mutate(town = str_to_lower(town)) %>% 
      select(town:ovr_65c, tot_benzo_2017) %>% 
      filter(tot_benzo_2017 != 0) %>% 
      mutate(benzo_rate_per_65 = tot_benzo_2017 / ovr_65c),
    by = c("TOWN" = "town")
    ) %>% 
  left_join(
    updated_model_df %>% 
      filter(year == 2017) %>% 
      select(TOWN, tot_benzo),
    by = "TOWN"
  )


raw_benzo_map <- map_w_benzo_pres %>%
  ggplot() +
  geom_sf(aes(fill = benzo_rate_per_65), color = "black") +
  scale_fill_viridis_c(option = "D", name = "") +
  theme(axis.text.x = element_blank(), axis.text.y = element_blank()) +
  ggtitle("Medicare benzodiazepine prescription per residents aged 65+\n2017 - Raw")
eb_benzo_map <- map_w_benzo_pres %>%
  ggplot() +
  geom_sf(aes(fill = tot_benzo), color = "black") +
  scale_fill_viridis_c(option = "D", name = "") +
  theme(axis.text.x = element_blank(), axis.text.y = element_blank()) +
  ggtitle("Medicare benzodiazepine prescription per residents aged 65+\n2017 - EB Smoothed")
benzo_map_grid <- plot_grid(raw_benzo_map, eb_benzo_map, ncol=1)
#save_plot(
#  filename= "../../figures/tidy_figures/raw_vs_eb_smoothed_benzo_map.png",
#  benzo_map_grid,
#  base_width = 8,
#  base_height = 8
#  )


mod_df_death_rate <- mod_df_count %>% 
  mutate(year=year+1) %>% 
  select(city_death:death_count_next_year, fin_pred, tot_pop) %>% 
  mutate(
    actual_death_rate = death_count_next_year * 10000/ tot_pop,
    pred_death_rate = fin_pred * 10000/ tot_pop,
    town_col = case_when(
      city_death == "ayer" ~ "Ayer",
      city_death == "gardner" ~ "Gardner",
      city_death == "worcester" ~ "Worcester",
      city_death == "fall river" ~ "Fall River",
      TRUE ~ "Other"
    ),
    town_shape = ifelse(city_death %in% c("ayer", "gardner", "worcester", "fall river"), 1.5, 0.5)
  )


updated_model_deal_rate <- updated_model_df %>% 
  mutate(year = year + 1) %>% 
  select(TOWN:death_rate_next_yr, fin_pred) %>% 
  mutate(
    death_rate_next_yr = death_rate_next_yr * 10000,
    fin_pred = exp(fin_pred) * 10000,
    town_col = case_when(
      TOWN == "ayer" ~ "Ayer",
      TOWN == "gardner" ~ "Gardner",
      TOWN == "worcester" ~ "Worcester",
      TOWN == "fall river" ~ "Fall River",
      TRUE ~ "Other"
      )#,
    #town_shape = ifelse(TOWN %in% c("ayer", "gardner", "worcester", "fall river"), 1.5, 0.5)
    )
updated_model_deal_rate 

mod_df_death_rate %>% 
  arrange(desc(actual_death_rate))
mod_df_death_rate %>% 
  filter(year == 2018) %>% 
  arrange(desc(pred_death_rate))


mod_df_death_rate_gath <- mod_df_death_rate %>% 
  select(city_death:year, actual_death_rate:pred_death_rate, town_col) %>% 
  gather(key="measure", value="value", actual_death_rate:pred_death_rate) %>% 
  mutate(measure = ifelse(measure=="actual_death_rate", "Actual", "Predicted")) 

updated_model_death_rate_gath <-updated_model_deal_rate %>% 
  pivot_longer(death_rate_next_yr:fin_pred, names_to = "measure", values_to = "value") %>% 
  mutate(measure = ifelse(str_detect(measure, "fin_pred"), "Predicted", "Actual"))

death_rate_comp_plot <- mod_df_death_rate_gath %>% 
  filter(town_col == "Other") %>% 
  ggplot(aes(year, value, group = city_death, color = town_col)) +
  geom_line(alpha = 0.5) +
  geom_line(
    data = mod_df_death_rate_gath %>% filter(town_col != "Other"),
    aes(year, value, group = city_death, color = town_col),
    size = 2.5
    ) +
  facet_wrap(~measure) +
  xlab("Year") +
  ylab("") +
  theme(
    axis.text.x = element_text(size = 20),
    axis.text.y = element_text(size = 20),
    axis.title = element_text(size = 20),
    plot.title = element_text(size = 22),
    strip.text.x = element_text(size = 20),
    legend.text = element_text(size = 20),
    legend.title = element_text(size = 20)
    ) +
  ggtitle("Actual v Predicted opioid overdose death rate per town\nRate per 10k town residents") +
  scale_color_manual(values = c("#1b9e77", "#d95f02",  "#7570b3", "grey50","#e7298a"), name = "Towns")
death_rate_comp_plot

updated_model_death_rate_gath %>% 
  filter(town_col == "Other") %>% 
  ggplot(aes(year, value, group = TOWN, color = town_col)) +
  geom_line(alpha = 0.5) +
  geom_line(
    data = updated_model_death_rate_gath %>% filter(town_col != "Other"),
    aes(year, value, group = TOWN, color = town_col),
    size = 2.5
    ) +
  facet_wrap(~measure) +
  xlab("Year") +
  ylab("") +
  theme(
    axis.text.x = element_text(size = 20),
    axis.text.y = element_text(size = 20),
    axis.title = element_text(size = 20),
    plot.title = element_text(size = 22),
    strip.text.x = element_text(size = 20),
    legend.text = element_text(size = 20),
    legend.title = element_text(size = 20)
    ) +
  ggtitle("Actual v Predicted opioid overdose death rate per town\nRate per 10k town residents") +
  scale_color_manual(values = c("#1b9e77", "#d95f02",  "#7570b3", "grey50","#e7298a"), name = "Towns")

both_mod_death_rate <- mod_df_death_rate_gath %>% 
  mutate(model = "Raw Counts") %>% 
  bind_rows(
    updated_model_death_rate_gath %>%
      mutate(
        model = "EB Smoothed"
        ) %>% 
      rename(city_death = TOWN)
    ) %>% 
   mutate(
    model_f = factor(model, levels = c("Raw Counts",  "EB Smoothed"))
    )

both_models_death_rate_plot <- both_mod_death_rate %>% 
  filter(town_col == "Other") %>% 
  ggplot(aes(year, value, group = city_death, color = town_col)) +
  geom_line(alpha = 0.5) +
  geom_line(
    data = both_mod_death_rate %>% filter(town_col != "Other"),
    aes(year, value, group = city_death, color = town_col),
    size = 2.5
    ) +
  facet_grid(model_f ~ measure) +
  xlab("Year") +
  ylab("") +
  theme(
    axis.text.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    axis.title = element_text(size = 16),
    plot.title = element_text(size = 18),
    strip.text.x = element_text(size = 16),
    strip.text.y = element_text(size = 16),
    legend.text = element_text(size = 16),
    legend.title = element_text(size = 16)
    ) +
  ggtitle("Actual v Predicted opioid overdose death rate per town\nRate per 10k town residents") +
  scale_color_manual(values = c("#1b9e77", "#d95f02",  "#7570b3", "grey50","#e7298a"), name = "Towns")
both_models_death_rate_plot

save_plot(
  filename= "../../figures/tidy_figures/actual_and_pred_deathrate_comp_eb_smooth_and_raw.png",
  both_models_death_rate_plot,
  base_height = 12,
  base_width = 14
  )

```

